import type { Metadata } from "next";
import "@repo/config-tailwind/globals.css";
import { Button } from "@repo/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-dvh bg-blue-500 text-white">
        {children}
        <Button>OPA</Button>
      </body>
    </html>
  );
}
